// <auto-generated />
using System;
using FA.JustBlog.Core.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FA.JustBlog.Core.Migrations
{
    [DbContext(typeof(JustBlogContext))]
    [Migration("20230417093714_db101")]
    partial class db101
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FA.JustBlog.Core.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UrlSlug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Categorys", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "If you're completely new to Entity Framework, we recommend you to learn Entity Framework basics first and gradually move forward.",
                            Name = "EF Basics",
                            UrlSlug = "ef-basics"
                        },
                        new
                        {
                            Id = 2,
                            Description = "If you want to use or currently Entity Framework 6.x with existing database then learn Entity Framework 6 Database-First Approach in this section.",
                            Name = "EF 6 DB-First",
                            UrlSlug = "ef-6-db-first"
                        },
                        new
                        {
                            Id = 3,
                            Description = "If you are using DDD (Domain Driven Design) for your application then learn Entity Framework 6 Code-First Approach in this section.",
                            Name = "EF 6 Code-First",
                            UrlSlug = "ef-6-code-first"
                        });
                });

            modelBuilder.Entity("FA.JustBlog.Core.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CommentHeader")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CommentTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2023, 4, 17, 16, 37, 13, 596, DateTimeKind.Local).AddTicks(3600));

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("UsingIdentityUserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UsingIdentityUserId");

                    b.ToTable("Comments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommentHeader = "tai sao",
                            CommentText = "Sao bạn lại đăng thế",
                            CommentTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = 1,
                            UsingIdentityUserId = "97571dcc-079e-4c3a-ba9b-bbde3d03a03d"
                        },
                        new
                        {
                            Id = 2,
                            CommentHeader = "tai sao m vô lý thế",
                            CommentText = "Sao bạn lại đăng thế thế",
                            CommentTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = 1,
                            UsingIdentityUserId = "97571dcc-079e-4c3a-ba9b-bbde3d03a03d"
                        },
                        new
                        {
                            Id = 3,
                            CommentHeader = "tai sao cho điểm thấp",
                            CommentText = "Sao bạn lại đăng thế kém z",
                            CommentTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = 2,
                            UsingIdentityUserId = "97571dcc-079e-4c3a-ba9b-bbde3d03a03d"
                        },
                        new
                        {
                            Id = 4,
                            CommentHeader = "tai sao hả",
                            CommentText = "Sao bạn lại đăng thế hả",
                            CommentTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = 3,
                            UsingIdentityUserId = "97571dcc-079e-4c3a-ba9b-bbde3d03a03d"
                        },
                        new
                        {
                            Id = 5,
                            CommentHeader = "tai sao ??????",
                            CommentText = "Sao bạn lại đăng thế chứ",
                            CommentTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = 3,
                            UsingIdentityUserId = "97571dcc-079e-4c3a-ba9b-bbde3d03a03d"
                        },
                        new
                        {
                            Id = 6,
                            CommentHeader = "why",
                            CommentText = "Fuck",
                            CommentTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = 3,
                            UsingIdentityUserId = "97571dcc-079e-4c3a-ba9b-bbde3d03a03d"
                        },
                        new
                        {
                            Id = 7,
                            CommentHeader = "Woww",
                            CommentText = "Xinj quas",
                            CommentTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = 3,
                            UsingIdentityUserId = "21842bcb-fae8-4c00-9c33-de997d4e8103"
                        },
                        new
                        {
                            Id = 8,
                            CommentHeader = "!0 diem",
                            CommentText = "te qua",
                            CommentTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = 3,
                            UsingIdentityUserId = "21842bcb-fae8-4c00-9c33-de997d4e8103"
                        });
                });

            modelBuilder.Entity("FA.JustBlog.Core.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("PostContent")
                        .IsRequired()
                        .HasMaxLength(500000000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PostedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Published")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("Rate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("RateCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("UrlSlug")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsingIdentityUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UsingIdentityUserId");

                    b.ToTable("Posts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Modified = new DateTime(2023, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Entity Framework is an open-source ORM framework for .NET applications supported by Microsoft. It enables developers to work with data using objects of domain specific classes without focusing on the underlying database tables and columns where this data is stored. With the Entity Framework, developers can work at a higher level of abstraction when they deal with data.",
                            PostedOn = new DateTime(2023, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = true,
                            Rate = 0.4m,
                            RateCount = 10m,
                            ShortDescription = " to save or retrieve application data from the underlying database. We used to open a connection to the database, create a DataSet to fetch or submit the data to the database, convert data from the DataSet to .NET objects or vice-versa to apply business rules. This was a cumbersome and error prone process.",
                            Title = "What is Entity Framework?",
                            TotalRate = 25m,
                            UrlSlug = "what-is-entity-framework",
                            UsingIdentityUserId = "97571dcc-079e-4c3a-ba9b-bbde3d03a03d",
                            ViewCount = 5
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Modified = new DateTime(2023, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Let's understand the above EF workflow: To insert data, add a domain object to a context and call the SaveChanges() method. EF API will build an appropriate INSERT command and execute it to the database.  To read data, execute the LINQ-to-Entities query in your preferred language (C#/VB.NET). EF API will convert this query into SQL query for the underlying relational database and execute it.",
                            PostedOn = new DateTime(2023, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = true,
                            Rate = 0.8m,
                            RateCount = 200m,
                            ShortDescription = "First of all, you need to define your model. Defining the model includes defining your domain classes, context class derived from DbContext, and configurations (if any). EF will perform CRUD operations based on your model.",
                            Title = "Basic Workflow in Entity Framework",
                            TotalRate = 250m,
                            UrlSlug = "basic-workflow-in-entity-framework",
                            UsingIdentityUserId = "97571dcc-079e-4c3a-ba9b-bbde3d03a03d",
                            ViewCount = 50
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Modified = new DateTime(2023, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "EF 6 Database-First and Code-First Features Creating Entity Data Model from your existing database Querying data using LINQ Saving data Using existing stored procedures, views, and table-valued functions CRUD operations using stored procedures  Optimistic concurrency & transactions support Supports Spatial Data Types Connection resiliency  Asynchronous query and save  Code-based configuration  Database command logging  Database command interception  ",
                            PostedOn = new DateTime(2023, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = true,
                            Rate = 0.6666666666666666666666666667m,
                            RateCount = 200m,
                            ShortDescription = "Welcome to Entity Framework 6 database-first tutorials section. Here, you will learn how to use Entity Framework 6 with the existing database of your application. It starts from creating an Entity Data Model from your existing database and it will show you how to save and query data using Entity Framework 6.x.",
                            Title = "Entity Framework 6 Introduction",
                            TotalRate = 300m,
                            UrlSlug = "entity-framework-6-introduction",
                            UsingIdentityUserId = "97571dcc-079e-4c3a-ba9b-bbde3d03a03d",
                            ViewCount = 60
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Modified = new DateTime(2023, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Here, we are going to create an Entity Data Model (EDM) for an existing database in database-first approach and understand the basic building blocks.    Entity Framework uses EDM for all the database-related operations. Entity Data Model is a model that describes entities and the relationships between them. Let's create a simple EDM for the School database using Visual Studio (2012\\2015\\2017) and Entity Framework 6.",
                            PostedOn = new DateTime(2023, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = false,
                            Rate = 0.6666666666666666666666666667m,
                            RateCount = 300m,
                            ShortDescription = "Here, we are going to create an Entity Data Model (EDM) for an existing database in database-first approach and understand the basic building blocks.    Entity Framework uses EDM for all the database-related operations. Entity Data Model is a model that describes entities and the relationships between them. Let's create a simple EDM for the School database using Visual Studio (2012\\2015\\2017) and Entity Framework 6.",
                            Title = "Creating an Entity Data Model",
                            TotalRate = 450m,
                            UrlSlug = "creating-an-entity-data-model",
                            UsingIdentityUserId = "21842bcb-fae8-4c00-9c33-de997d4e8103",
                            ViewCount = 90
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Modified = new DateTime(2023, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Add	Added entity type	Adds the given entity to the context with the Added state. When the changes are saved, the entities in the Added states are inserted into the database. After the changes are saved, the object state changes to Unchanged.\r\n\r\nExample:\r\ndbcontext.Students.Add(studentEntity)",
                            PostedOn = new DateTime(2023, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = false,
                            Rate = 0.5555555555555555555555555556m,
                            RateCount = 250m,
                            ShortDescription = "The DbSet class represents an entity set that can be used for create, read, update, and delete operations.\r\n\r\nThe context class (derived from DbContext) must include the DbSet type properties for the entities which map to database tables and views.",
                            Title = "DbSet in Entity Framework 6",
                            TotalRate = 450m,
                            UrlSlug = "dbset-in-entity-framework-6",
                            UsingIdentityUserId = "21842bcb-fae8-4c00-9c33-de997d4e8103",
                            ViewCount = 90
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Modified = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "In the Entity Framework, there are two persistence scenarios to save an entity data: connected and disconnected. In the connected scenario, the same instance of DbContext is used in retrieving and saving entities, whereas this is different in the disconnected scenario. In this chapter, you will learn about saving data in the connected scenario.",
                            PostedOn = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = false,
                            Rate = 0.8m,
                            RateCount = 360m,
                            ShortDescription = "Saving entity data in the connected scenario is a fairly easy task because the context automatically tracks the changes that happened on the entity during its lifetime.\r\n\r\nHere, we will use the same EDM for CRUD operations which we created in the Create Entity Data Model chapter. An entity which contains data in its scalar property will be either inserted, updated or deleted, based on its EntityState.",
                            Title = "Saving Data in the Connected Scenario",
                            TotalRate = 450m,
                            UrlSlug = "saving-data-in-the-connected-scenario",
                            UsingIdentityUserId = "21842bcb-fae8-4c00-9c33-de997d4e8103",
                            ViewCount = 90
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Modified = new DateTime(2023, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Language-Integrated Query (LINQ) is a powerful query language introduced in Visual Studio 2008. As the name suggests, LINQ-to-Entities queries operate on the entity set (DbSet type properties) to access the data from the underlying database. You can use the LINQ method syntax or query syntax when querying with EDM. Visit LINQ Tutorials to learn LINQ step-by-step.",
                            PostedOn = new DateTime(2023, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = false,
                            Rate = 0.6m,
                            RateCount = 300m,
                            ShortDescription = "You can build and execute queries using Entity Framework to fetch the data from the underlying database. EF 6 supports different types of queries which in turn convert into SQL queries for the underlying database.",
                            Title = "Querying in Entity Framework",
                            TotalRate = 500m,
                            UrlSlug = "querying-in-entity-framework",
                            UsingIdentityUserId = "21842bcb-fae8-4c00-9c33-de997d4e8103",
                            ViewCount = 100
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Modified = new DateTime(2022, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "SELECT TOP (1) \r\n[Extent1].[StudentID] AS [StudentID], \r\n[Extent1].[StudentName] AS [StudentName], \r\n[Extent2].[StandardId] AS [StandardId], \r\n[Extent2].[StandardName] AS [StandardName], \r\n[Extent2].[Description] AS [Description]\r\nFROM  [dbo].[Student] AS [Extent1]\r\nLEFT OUTER JOIN [dbo].[Standard] AS [Extent2] ON [Extent1].[StandardId] = [Extent2].[StandardId]\r\nWHERE 'Bill' = [Extent1].[StudentName]",
                            PostedOn = new DateTime(2022, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = false,
                            Rate = 0.6666666666666666666666666667m,
                            RateCount = 3000m,
                            ShortDescription = "Eager loading is the process whereby a query for one type of entity also loads related entities as part of the query, so that we don't need to execute a separate query for related entities. Eager loading is achieved using the Include() method.",
                            Title = "Eager Loading in Entity Framework",
                            TotalRate = 4500m,
                            UrlSlug = "eager-loading-in-entity-framework",
                            UsingIdentityUserId = "21842bcb-fae8-4c00-9c33-de997d4e8103",
                            ViewCount = 900
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Modified = new DateTime(2023, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "We can disable lazy loading for a particular entity or a context. To turn off lazy loading for a particular property, do not make it virtual. To turn off lazy loading for all entities in the context, set its configuration property to false.",
                            PostedOn = new DateTime(2023, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = false,
                            Rate = 0.6666666666666666666666666667m,
                            RateCount = 300m,
                            ShortDescription = "Lazy loading is delaying the loading of related data, until you specifically request for it. It is the opposite of eager loading. For example, the Student entity contains the StudentAddress entity. In the lazy loading, the context first loads the Student entity data from the database, then it will load the StudentAddress entity when we access the StudentAddress property as shown below.",
                            Title = "Lazy Loading in Entity Framework",
                            TotalRate = 450m,
                            UrlSlug = "lazy-loading-in-entity-framework",
                            UsingIdentityUserId = "21842bcb-fae8-4c00-9c33-de997d4e8103",
                            ViewCount = 90
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Modified = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Here, we are going to create an Entity Data Model (EDM) for an existing database in database-first approach and understand the basic building blocks.    Entity Framework uses EDM for all the database-related operations. Entity Data Model is a model that describes entities and the relationships between them. Let's create a simple EDM for the School database using Visual Studio (2012\\2015\\2017) and Entity Framework 6.",
                            PostedOn = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = false,
                            Rate = 0.6666666666666666666666666667m,
                            RateCount = 300m,
                            ShortDescription = "Here, we are going to create an Entity Data Model (EDM) for an existing database in database-first approach and understand the basic building blocks.    Entity Framework uses EDM for all the database-related operations. Entity Data Model is a model that describes entities and the relationships between them. Let's create a simple EDM for the School database using Visual Studio (2012\\2015\\2017) and Entity Framework 6.",
                            Title = "Explicit Loading in Entity Framework",
                            TotalRate = 450m,
                            UrlSlug = "explicit-loading-in-entity-framework",
                            UsingIdentityUserId = "21842bcb-fae8-4c00-9c33-de997d4e8103",
                            ViewCount = 90
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Modified = new DateTime(2023, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Language-Integrated Query (LINQ) is a powerful query language introduced in Visual Studio 2008. As the name suggests, LINQ-to-Entities queries operate on the entity set (DbSet type properties) to access the data from the underlying database. You can use the LINQ method syntax or query syntax when querying with EDM. Visit LINQ Tutorials to learn LINQ step-by-step.",
                            PostedOn = new DateTime(2023, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = false,
                            Rate = 0.6m,
                            RateCount = 300m,
                            ShortDescription = "You can build and execute queries using Entity Framework to fetch the data from the underlying database. EF 6 supports different types of queries which in turn convert into SQL queries for the underlying database.",
                            Title = "Querying in Entity Core",
                            TotalRate = 500m,
                            UrlSlug = "querying-in-entity-core",
                            UsingIdentityUserId = "21842bcb-fae8-4c00-9c33-de997d4e8103",
                            ViewCount = 100
                        });
                });

            modelBuilder.Entity("FA.JustBlog.Core.Models.PostTagMap", b =>
                {
                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.HasKey("TagId", "PostId");

                    b.HasIndex("PostId");

                    b.ToTable("PostTagMap", (string)null);

                    b.HasData(
                        new
                        {
                            TagId = 2,
                            PostId = 1
                        },
                        new
                        {
                            TagId = 1,
                            PostId = 1
                        },
                        new
                        {
                            TagId = 3,
                            PostId = 1
                        },
                        new
                        {
                            TagId = 3,
                            PostId = 2
                        },
                        new
                        {
                            TagId = 3,
                            PostId = 3
                        },
                        new
                        {
                            TagId = 3,
                            PostId = 4
                        },
                        new
                        {
                            TagId = 1,
                            PostId = 5
                        },
                        new
                        {
                            TagId = 1,
                            PostId = 6
                        },
                        new
                        {
                            TagId = 1,
                            PostId = 7
                        },
                        new
                        {
                            TagId = 1,
                            PostId = 8
                        },
                        new
                        {
                            TagId = 1,
                            PostId = 9
                        },
                        new
                        {
                            TagId = 1,
                            PostId = 10
                        });
                });

            modelBuilder.Entity("FA.JustBlog.Core.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Count")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UrlSlug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Tags", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Count = 1,
                            Description = "Querying in Entity Framework Core remains the same as in EF 6.x, with more optimized SQL queries and the ability to include C#/VB.NET functions into LINQ-to-Entities queries",
                            Name = "Querying in Entity Framework Core",
                            UrlSlug = "querying-in-ef-core"
                        },
                        new
                        {
                            Id = 2,
                            Count = 2,
                            Description = "Entity Framework Core provides different ways to add, update, or delete data in the underlying database",
                            Name = "Entity Framework Core: Saving Data in Connected Scenario",
                            UrlSlug = "saving-data-in-connected-scenario-in-ef-core"
                        },
                        new
                        {
                            Id = 3,
                            Count = 3,
                            Description = "Conventions are default rules using which Entity Framework builds a model based on your domain (entity) classes",
                            Name = "Conventions in Entity Framework Core",
                            UrlSlug = "conventions-in-ef-core"
                        });
                });

            modelBuilder.Entity("FA.JustBlog.Core.Models.UsingIdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "97571dcc-079e-4c3a-ba9b-bbde3d03a03d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7d6e8a26-1ac5-4a4a-a6c6-da1f8e23d6a0",
                            Email = "vietContributor@gmail.com",
                            EmailConfirmed = true,
                            Firstname = "Viet",
                            LastName = "Le",
                            LockoutEnabled = false,
                            NormalizedEmail = "VIETCONTRIBUTOR@GMAIL.COM",
                            NormalizedUserName = "VIETCONTRIBUTOR@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEJ51SmQrANatorjKkODvG7wRz8i73uIAUIHAmXRldg8ikayfZiaDQvbSOuY+XFPiJQ==",
                            PhoneNumber = "0985695635",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "2fa1337f-32b3-4078-b650-1decf9470b37",
                            TwoFactorEnabled = false,
                            UserName = "vietContributor@gmail.com"
                        },
                        new
                        {
                            Id = "21842bcb-fae8-4c00-9c33-de997d4e8103",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "90badfde-c2cf-44ae-9749-e6d75472f370",
                            Email = "vietBlogOwner@gmail.com",
                            EmailConfirmed = true,
                            Firstname = "Khi",
                            LastName = "nguyen",
                            LockoutEnabled = false,
                            NormalizedEmail = "VIETBLOGOWNER@GMAIL.COM",
                            NormalizedUserName = "VIETBLOGOWNER@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEGf8AICmlUDtMuw9p1TPGYB0/OH8X60Ud06sUakpWa+Tpu2IJAZvF6Ht7DxsYeWEjA==",
                            PhoneNumber = "045896589",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "cb1db7cb-33d7-42d1-8f1d-1c69ebe6f70c",
                            TwoFactorEnabled = false,
                            UserName = "vietBlogOwner@gmail.com"
                        },
                        new
                        {
                            Id = "21811bcb-fae8-4c00-9c33-de997d4e8107",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "308ea6d0-3fbd-4a02-8242-f15caa4f8356",
                            Email = "vietUser@gmail.com",
                            EmailConfirmed = true,
                            Firstname = "Viet",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "VIETUSER@GMAIL.COM",
                            NormalizedUserName = "VIETUSER@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEGf8AICmlUDtMuw9p1TPGYB0/OH8X60Ud06sUakpWa+Tpu2IJAZvF6Ht7DxsYeWEjA==",
                            PhoneNumber = "0922556369",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "a4d834a9-8c02-4b18-9fc1-2158620b349a",
                            TwoFactorEnabled = false,
                            UserName = "vietUser.com"
                        },
                        new
                        {
                            Id = "b0446349-235d-4b0f-a8e9-87382a82923f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2607a386-1e9c-4812-abda-5926e8629430",
                            Email = "user@gmail.com",
                            EmailConfirmed = true,
                            Firstname = "Toan",
                            LastName = "Nguyen",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@GMAIL.COM",
                            NormalizedUserName = "USER@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAED7S01cmZYmeJEKd7/wVP+HGOCSHbR/Xl2NRWyWTXB6JbwfXREcO2D908cRKtFG2Ag==",
                            PhoneNumber = "0458796598",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "f50735fd-3006-4b33-b158-f61aadd38582",
                            TwoFactorEnabled = false,
                            UserName = "user@gmail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "db1782c7-bf14-41f7-bc1f-950128ecb3bd",
                            ConcurrencyStamp = "b11bbed6-4919-4f52-a4b1-c45091a8fbf0",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "db5782c7-bf14-41f7-bc1f-950128ecb3bb",
                            ConcurrencyStamp = "b31bbed6-4919-4f52-a4b1-c45091a8fbf0",
                            Name = "Blog Owner",
                            NormalizedName = "BLOG OWNER"
                        },
                        new
                        {
                            Id = "e94a9bca-5a7a-4806-b8cd-97e9075ff13a",
                            ConcurrencyStamp = "e22ebaa4-db51-4cb3-8f37-ad4ba73b0e1e",
                            Name = "Contributor",
                            NormalizedName = "CONTRIBUTOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "97571dcc-079e-4c3a-ba9b-bbde3d03a03d",
                            RoleId = "e94a9bca-5a7a-4806-b8cd-97e9075ff13a"
                        },
                        new
                        {
                            UserId = "21842bcb-fae8-4c00-9c33-de997d4e8103",
                            RoleId = "db5782c7-bf14-41f7-bc1f-950128ecb3bb"
                        },
                        new
                        {
                            UserId = "21811bcb-fae8-4c00-9c33-de997d4e8107",
                            RoleId = "db1782c7-bf14-41f7-bc1f-950128ecb3bd"
                        },
                        new
                        {
                            UserId = "b0446349-235d-4b0f-a8e9-87382a82923f",
                            RoleId = "db1782c7-bf14-41f7-bc1f-950128ecb3bd"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FA.JustBlog.Core.Models.Comment", b =>
                {
                    b.HasOne("FA.JustBlog.Core.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FA.JustBlog.Core.Models.UsingIdentityUser", null)
                        .WithMany("Comments")
                        .HasForeignKey("UsingIdentityUserId");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("FA.JustBlog.Core.Models.Post", b =>
                {
                    b.HasOne("FA.JustBlog.Core.Models.Category", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FA.JustBlog.Core.Models.UsingIdentityUser", null)
                        .WithMany("Posts")
                        .HasForeignKey("UsingIdentityUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FA.JustBlog.Core.Models.PostTagMap", b =>
                {
                    b.HasOne("FA.JustBlog.Core.Models.Post", "Post")
                        .WithMany("PostTagMaps")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FA.JustBlog.Core.Models.Tag", "Tag")
                        .WithMany("PostTagMaps")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FA.JustBlog.Core.Models.UsingIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FA.JustBlog.Core.Models.UsingIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FA.JustBlog.Core.Models.UsingIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FA.JustBlog.Core.Models.UsingIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FA.JustBlog.Core.Models.Category", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("FA.JustBlog.Core.Models.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("PostTagMaps");
                });

            modelBuilder.Entity("FA.JustBlog.Core.Models.Tag", b =>
                {
                    b.Navigation("PostTagMaps");
                });

            modelBuilder.Entity("FA.JustBlog.Core.Models.UsingIdentityUser", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
